apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMDcuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImMzVnJaV1Z5Z
type: kubernetes.io/dockerconfigjson